version: 2
jobs:
  test_gui:
    docker:
      - image: circleci/elixir:1.6
      - image: circleci/postgres:10.1-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: uptime_gui_test
          POSTGRES_PASSWORD: postgres

    working_directory: ~/repo/

    steps:
      - checkout
      - run: cd uptime_gui && mix local.rebar --force && mix local.hex --force && mix deps.get
      - run: cd uptime_gui && mix test

  test_backend:
    docker:
      - image: circleci/elixir:1.6

    working_directory: ~/repo/

    steps:
      - checkout
      - run: cd backend && mix local.rebar --force && mix local.hex --force && mix deps.get
      - run: cd backend && mix test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test_gui
      - test_backend
